server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://123.57.74.173:3306/study_room?serverTimezone=GMT%2B8
    username: study_room
    password: lx200115
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB


mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag  # 逻辑删除， 1 删除 0 不删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto  # 使用雪花算法自动产生id
oss:
  accessKey: xrrsPBTq16bdQQSY1Ksc5tlRfXuj_KC8IofxKTOz
  secretKey: pPyedjA7vxm4dfEzPW9A3wWyF8yD4P6n3UYDjzce
  bucket: lx-study-room
  CDN: rnt1z37kr.hb-bkt.clouddn.com